#!/usr/bin/perl

use strict;
use warnings;

while(<>){
    chomp $_;

    if (/num(\d)(\d)','(\d)*'/) {
	if (defined $3) {
	    print "($1) -> $3\t";
	    if ($1 == $3) {
		print "OK\n";
	    } else {
		print "NG\n";
	    }
	} else {
	    print "($1) -> _\tNG\n";
	}
    }

    if (/circle/) {
	if (/circle(\d)''○'/) {
	    print "(circle) -> ○\tOK\n";
	} else {
	    print "(circle) -> .\tNG\n";
	}
    }

    if (/triangle/) {
	if (/triangle(\d)''△'/) {
	    print "(triangle) -> △\tOK\n";
	} else {
	    print "(triangle) -> .\tNG\n";
	}
    }

    if (/'x(\d)'/) {
	if (/'x(\d)'''×'/) {
	    print "(checked) -> ×\tOK\n";
	} else {
	    print "(checked) -> .\tNG\n";
	}
    }
}
