#!/usr/bin/perl

use strict;
use warnings;
use utf8;

# The input must be utf8
binmode(STDIN,  ":utf8");   # convert the utf8 input to the internal expression
# convert internal expression to utf8 for output
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");

while(<>){
    chomp $_;

    if (/num(\d)(\d)','(\d)*?'/) {
        if (defined $3) {
            print "($1) -> $3\t";
            if ($1 == $3) {
                print "OK\n";
            } else {
                print "NG\n";
            }
        } else {
            print "($1) -> _\tNG\n";
        }
    }

    if (/circle/) {
        if (/circle(\d)','○'/) {
            print "(circle) -> ○\tOK\n";
        } else {
            print "(circle) -> .\tNG\n";
        }
    }

    if (/triangle/) {
        if (/triangle(\d)','△'/) {
            print "(triangle) -> △\tOK\n";
        } else {
            print "(triangle) -> .\tNG\n";
        }
    }

    if (/'x(\d)'/) {
        if (/'x(\d)','×'/) {
            print "(cross) -> ×\tOK\n";
        } else {
            print "(cross) -> .\tNG\n";
        }
    }

    if (/'chk(\d)'/) {
        if (/'chk(\d)','✓'/) {
            print "(checked) -> ✓\tOK\n";
        } else {
            print "(checked) -> .\tNG\n";
        }
    }
}
