
test:
	./test-sheetreader.sh ./samples/fax-01.tif 2> /dev/null
	./test-sheetreader.sh ./samples/fax-02.tif 2> /dev/null
	./test-sheetreader.sh ./samples/fax-03.tif 2> /dev/null
	./test-sheetreader.sh ./samples/fax-04.tif 2> /dev/null
